GET https://test.wikipedia.org/api/rest_v1/page/mobile-sections-lead/Ampersand_%26_title

# Mercury

# endpoint: https://en.wikipedia.org/api/rest_v1

GET https://en.wikipedia.org/api/rest_v1/page/mobile-sections-lead/Mecyclothorax_aa

# sections
GET https://en.wikipedia.org/api/rest_v1/page/mobile-sections-remaining/Mecyclothorax_aa


# preview dialog
GET https://en.wikipedia.org/api/rest_v1/page/summary/LIGO




## Local
GET http://localhost:8888/mediawiki/api.php?action=query&titles=Main%20Page&prop=revisions&rvprop=content&format=json


## prelude
GET http://localhost:8888/mediawiki/api.php?action=query&titles=prelude&prop=revisions&rvprop=content&format=json
