@startuml

title Simple communication example

component Fresco

note right of [Fresco]
  A note can also
  be on several lines
end note

component sdwebimage

note right of [sdwebimage]
  A note can also
  be on several lines
end note


@enduml